version: "3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=golang
  golang:
    build:
      context: ./
      dockerfile: Dockerfile-for-tests
